import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

// -------------------------------------------------------------------
// 🚀 FAVICON FIX: Dynamic injection to use logo from the 'src' folder
// -------------------------------------------------------------------

// 1. Import the logo. Webpack/CRA will resolve this path correctly during the build.
// NOTE: Make sure the path './images/logo.png' is correct relative to this index.js file.
import SamgyupLogo from './images/logo.png'; 

// 2. Function to update or create the favicon link in the HTML head
function setFavicon(url) {
    let link = document.querySelector("link[rel~='icon']");
    if (!link) {
        // Create the link element if it doesn't exist
        link = document.createElement('link');
        link.rel = 'icon';
        document.getElementsByTagName('head')[0].appendChild(link);
    }
    // Set the href to the URL generated by Webpack/CRA for the imported logo
    link.href = url;
}

// 3. Execute the function immediately
setFavicon(SamgyupLogo);

// -------------------------------------------------------------------
// End Favicon Fix
// -------------------------------------------------------------------

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
